In [1]:
import numpy as np
import pandas as pd

a= np.array([1,2,3])

a

array([1, 2, 3])

In [2]:
type(a)

numpy.ndarray

In [3]:
np.shape(a)

(3,)

In [4]:
a[1]

2

In [7]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
b.shape

(3, 3)

In [9]:
c = np.zeros((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
d = np.ones((4,2))
d

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
f = np.full((5,2),7)
f

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

In [14]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
g = b [1:, 1:] 
g

array([[5, 6],
       [8, 9]])

In [15]:
g2=b[0:2, 0:2]
g2

array([[1, 2],
       [4, 5]])

In [16]:
g

array([[5, 6],
       [8, 9]])

In [17]:
g[1,1]

9

In [18]:
g[1,1] = 2021

In [19]:
g

array([[   5,    6],
       [   8, 2021]])

In [20]:
b

array([[   1,    2,    3],
       [   4,    5,    6],
       [   7,    8, 2021]])

In [21]:
b[1,1]=5050
g

array([[5050,    6],
       [   8, 2021]])

In [22]:
b

array([[   1,    2,    3],
       [   4, 5050,    6],
       [   7,    8, 2021]])

In [23]:
x = np.array([[1,2],
              [3,4]],
            dtype = np.float64)
y = np.array([[5,6],
             [7,8]],
            dtype = np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [24]:
print(np.add(x,y))


[[ 6.  8.]
 [10. 12.]]


In [28]:
comp = x+y == np.add(x,y)
comp

array([[ True,  True],
       [ True,  True]])

In [29]:
print(np.array_equal(x+y, np.add(x,y)))

True


In [30]:
print(x-y)

[[-4. -4.]
 [-4. -4.]]


In [31]:
print(np.array_equal(x-y,np.subtract(x,y)))

True


In [32]:
x*y

array([[ 5., 12.],
       [21., 32.]])

In [33]:
np.sum(x, axis=1)

array([3., 7.])

In [34]:
x

array([[1., 2.],
       [3., 4.]])

In [35]:
np.sum(x, axis=0)

array([4., 6.])